repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast  # Is it valid Python?
      - id: debug-statements # no debbuging statements used
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=6000']
      - id: check-case-conflict
      - id: check-json
      - id: pretty-format-json
        args: [ "--autofix" ]
        exclude: ^data/
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-executables-have-shebangs

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - "--profile=black"
          - "--filter-files"
          - "--line-length=120"

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.10
        args:
          - "--line-length=120"
